{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.secretStore.provider | nindent 4 }}
{{- end }}
