{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecrets.target.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        conversionStrategy: {{ .remoteRef.conversionStrategy | default "Default" }}
        decodingStrategy: {{ .remoteRef.decodingStrategy | default "None" }}
        metadataPolicy: {{ .remoteRef.metadataPolicy | default "None" }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
        {{- with .remoteRef.version }}
        version: {{ . }}
        {{- end }}
    {{- end }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
{{- end }}